### ISSUE TITLE
Issues in Attendance Controller

### ISSUE THREAD

**Issue by RainiWijewantha** [HRIS-M/HRIS#70]
"org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'attendanceController': Unsatisfied dependency expressed through field 'attendanceRepository': Error creating bean with name 'attendanceRepository' defined in com.hris.HRIS.repository.AttendanceRepository defined in @EnableMongoRepositories declared on MongoRepositoriesRegistrar.EnableMongoRepositoriesConfiguration: Could not create query for public abstract java.util.Optional com.hris.HRIS.repository.AttendanceRepository.findByEmail(java.lang.String); Reason: No property 'email' found for type 'AttendanceModel'  "

@PawaraLiyanage 
This is the error when running the project now. It has happened in the Attendance Controller. Please fix this issue.

**Comment by kavicastelo** [comment]
This error occurs because you don't have an email feild in `AttendenceModel`.
follow these steps to fix the problem.
1. Remove `findByEmail(String email)` and `deleteByEmail(String email);` from `AttendanceRepository`.
2. Remove `getAttendanceByEmail` from `AttendenceController`

or

1. Add `private String email;` property to the `AttendenceModel`

Request Changes for,
```java
    Optional<AttendanceModel> findByEmail(String email);

    Optional<AttendanceModel> deleteByEmail(String email);
```
```java
    @GetMapping("/get/email/{email}")
    public ResponseEntity<AttendanceModel> getAttendanceByEmail(@PathVariable String email) {
        Optional<AttendanceModel> attendanceModelOptional = attendanceRepository.findByEmail(email);

        return attendanceModelOptional.map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());
    }
```

**Comment by PawaraLiyanage** [comment]
Done,
Add email property.
